# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Thumbprints
email: info@thethumbprints.ca
description: >- # this means to ignore newlines until "baseurl:"
  Thumbprints is passionate about handmade authentic and real art work and
  sourcing it from the source and making it available to the Canadian People.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.thethumbprints.ca" # the base hostname & protocol for your site, e.g. http://example.com
logo_light: "/assets/images/logo-light.png"
logo_dark: "/assets/images/logo-dark.png"
logo: "/assets/images/logo-dark.png"
cloudinary_url: "https://res.cloudinary.com/mehtavd/image/upload"
social:
  links:
    - https://www.facebook.com/The-Thumbprints-941817292683454/
    - https://www.instagram.com/thethumbprints78/

# Collections
collections:
  artifacts:
    permalink: "/artifact/:title/"
    output: true
  posts:
    permalink: "/blog/:title/"
defaults:
  - scope:
      path: ""
      type: artifacts
    values:
      layout: artifact
  - scope:
      path: ""
      type: posts
    values:
      layout: post

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-menus
  - jekyll-archives
  - jekyll-paginate

# Jekyll archives
jekyll-archives:
  enabled:
    - categories
    - month
  layout: archive
  layouts:
    category: category-archive
    month: month-archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

# Jekyll paginate
paginate: 1
paginate_path: "/blog/page:num/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
