---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: document
  path: index.html
  label: Homepage
- type: directory
  path: _artifacts
  label: Artifacts
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - post
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
