---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: document
  path: index.html
  label: Homepage
- type: directory
  path: _artifacts
  label: Artifacts
  create: documents
  match: "**/*"
  templates:
  - artifact
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - post
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: ''
public_path: https://res.cloudinary.com/mehtavd/image/upload
front_matter_path: https://res.cloudinary.com/mehtavd/image/upload
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
